# Generated by Django 4.2 on 2024-12-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
